[build]
  publish = "public"
  command = "npm run build && npm run ipfs-deploy"

[context.production.environment]
  HUGO_VERSION = "0.58.1"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "https://skyue.netlify.com/*"
  to = "https://skyuehu.com/:splat"
  force = true